### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by chen-ysh** [Sangs3112/SimGNN#1]
请问作者，你在 AIDs 数据集上训练需要多久，为什么我使用 4090 显卡的训练速度这么慢，好几分钟一个 epoch
![image](https://github.com/user-attachments/assets/61df7122-dc08-4994-99c6-c2e12d13b9d5)

**Comment by Sangs3112** [comment]
是的，因为我的方向需要使用自己的数据集，所以无法使用batch。因此，我实现的SimGNN尽管使用了原文的三个数据集，但是我依然没有用batch，这才导致训练速度很慢。如果有需要的话，可以实现批处理，这样训练速度应该会大幅提升。

**Comment by xjwanghao** [comment]
请问作者，应当如何使用batch呢

**Comment by Sangs3112** [comment]
看 #3 ，我的建议是如果需要使用batch，最好就不要用自己下载的数据集，用官方的GED_Datasets会更加方便一些。。因为我曾尝试自己做数据集的batch，发现非常的麻烦，最后以失败告终。
