### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by chen-ysh** [Sangs3112/SimGNN#2]
为什么你的实现比原文的结果好这么多，请问有哪些修改吗

**Comment by Sangs3112** [comment]
是的，我主要关注了AIDS700nef上的结果，感觉跟原文结果一致我就直接用相同的配置跑了一下LINUX与IMDB数据集，跑出来的结果我就没管了。

**Comment by Sangs3112** [comment]
我的实验配置参见[utils/config.yml](https://github.com/Sangs3112/SimGNN/blob/master/utils/config.yml)，其中全部为SimGNN论文配置，剩余部分配置参考SimGNN的tensorflow实现。
