### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by xjwanghao** [Sangs3112/SimGNN#3]
作者您好，请问如何使用batch，提高速度呢

**Comment by Sangs3112** [comment]
我没有研究如何使用batch，如果需要改成batch的话，可以使用pyg中的GED_DATASET，那个里面好像自带了batch信息。

**Comment by Sangs3112** [comment]
如果您没有更多问题的话, 我将关闭这个Issue :)

**Comment by xjwanghao** [comment]
感谢作者的恢复，可以咨询下作者的硬件配置是什么吗？

**Comment by Sangs3112** [comment]
R9 7950X和4090

**Comment by xjwanghao** [comment]
感谢您的回答
