### ISSUE TITLE
关于论文的数据集问题

### ISSUE THREAD

**Issue by Q1DT** [Sangs3112/SimGNN#4]
Sangs3112您好，我下载了您提供的数据集并成功运行了代码，但是我在尝试更改为自有数据集时遇到了一个问题。您所提供的数据集中（以LINUX为例）的【processs】文件夹中的数据是如何生成的呢，我查看了其他论文中LINUX数据集，发现仅有gexf文件。希望能够得到您的解答谢谢。

**Comment by Sangs3112** [comment]
我提供的数据集与PyG中给出的GEDDataset是完全一样的, 主要是因为国内使用GEDDataset会自动从外网指定网址下载数据集, 但是因为一些网络问题下载不了, 所以我下载好了放到了云盘中, 避免了这个问题.
因此, process也是PyG官方提供的编码好的文件, 自己是无法修改这个process目录中的文件的, 如果想要自己制作新的数据集, 可以了解一下pkl格式, 将图编码在.pkl文件中读取即可

**Comment by Q1DT** [comment]
感谢您的回答，我已经建立了.pkl文件，但是在运行代码时发现，process文件夹中的.pt文件似乎是必不可少的，缺乏该文件会使得代码报错。还是以LINUX数据集为例，删除了该pt文件（LINUX_ged.pt）后，代码无法运行，提示缺少该文件：
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/LINUX/processed/LINUX_ged.pt'

**Comment by Q1DT** [comment]
> 我提供的数据集与PyG中给出的GEDDataset是完全一样的, 主要是因为国内使用GEDDataset会自动从外网指定网址下载数据集, 但是因为一些网络问题下载不了, 所以我下载好了放到了云盘中, 避免了这个问题. 因此, process也是PyG官方提供的编码好的文件, 自己是无法修改这个process目录中的文件的, 如果想要自己制作新的数据集, 可以了解一下pkl格式, 将图编码在.pkl文件中读取即可

感谢您的回答，我已经建立了.pkl文件，但是在运行代码时发现，process文件夹中的.pt文件似乎是必不可少的，缺乏该文件会使得代码报错。还是以LINUX数据集为例，删除了该pt文件（LINUX_ged.pt）后，代码无法运行，提示缺少该文件：
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/LINUX/processed/LINUX_ged.pt'

**Comment by Sangs3112** [comment]
修改了.pkl文件以后, dataset导入部分路径肯定都需要修改的, 不是简单的换一下文件资源就行的

**Comment by Q1DT** [comment]
> 修改了.pkl文件以后, dataset导入部分路径肯定都需要修改的, 不是简单的换一下文件资源就行的

感谢您的回复。我针对路径也做了修改（在config.py和config.yml文件中进行了修改）。我不明白的是GEDDataset所给出的数据中【process】文件夹内的文件是如何生成的，因为其中的文件（如.pt文件）是成功运行代码必不可少的。我在仿照上述数据集格式建立自有数据集，我已经建立gexf文件，pkl文件，文件内容的格式都是仿照LINUX建立，但是我目前仍无法运行，系统提示因为缺乏【process】文件夹中的pt文件，我检索了很久也没有搜到【process】中的文件是如何生成。

**Comment by Sangs3112** [comment]
那个文件我的理解是不能自己生成, 既然是PyG自带的, 就只能去PyG那边找找办法问了.这我也不清楚, 我没用到pt文件一样可以运行

**Comment by Sangs3112** [comment]
如果您没有更多问题的话, 我将关闭这个Issue
